
# api/config/routes.yaml
tasks_by_ekipa:
    path: /tasks-by-ekipa/{ekipa_id}
    methods: ['GET']
    defaults:
        _controller: App\Controller\TaskController::tasksByEkipa

tools_by_ekipa:
    path: /tools-by-ekipa/{ekipa_id}
    methods: ['GET']
    defaults:
        _controller: App\Controller\ToolController::toolsByEkipa

users_by_ekipa:
    path: /users-by-ekipa/{ekipa_id}
    methods: ['GET']
    defaults:
        _controller: App\Controller\UserController::usersByEkipa
user_login:
    path: /login
    methods: ['POST']
    defaults:
        _controller: App\Controller\UserController::userLogin


